import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Quicksand, Maven_Pro } from "next/font/google";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

const mavenPro = Maven_Pro({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-karma",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`bg-primary antialiased ${quicksand.variable} ${mavenPro.variable} relative h-[350vh]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
